# Generated by Django 5.2.1 on 2025-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_category_tag_event_eventgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.BooleanField(default=False, help_text='Does this event require a ticket?'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.PositiveIntegerField(blank=True, help_text='Price in NPR (only if ticket is required)', null=True),
        ),
    ]
